language: java
sudo: true
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
  - mvn clean package -Dspring.profiles.active=prod
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: to-you-do-api