--liquibase formatted sql
--changeset igor:V1_CREATE_USER_AND_TODO.01

CREATE TABLE "public"."todo"(
    id int8 generated by default as identity,
    descricao varchar(255) not null,
    concluido boolean,
    version int4 not null,
    primary key (id)
);

CREATE TABLE "public"."usuario" (
     id int8 generated by default as identity,
     username varchar(255) not null,
     password varchar(255),
     version int4,
     primary key (id)
);

alter table if exists "public"."usuario" add constraint UK_USERNAME unique (username);

--changeset igor:V1_INSERT_USER_ADMIN.01
insert into "public"."usuario" (username, password, version) values('admin@gmail.com', '$2a$10$hhXxbHy9ntosj./.qGzmW.T3UgRhinfj0.0ThN9SEqCJjGy0YB9Ty', 0);